### ISSUE TITLE
Swagger docs URL in readme

### ISSUE THREAD

**Issue by Anslem27** [Hero-API/HeroAPI#61]
Yeah just noticed the swagger docs link in the `readme`, uses the old api domain.

**Comment by OnlyRad** [comment]
Hi, my dear friend;
 We apologize for what happened and we are investigating the problem… You can visit our telegram channel to see the docks: [Docs-Telegram](https://t.me/HeroAPI)

**Comment by Anslem27** [comment]
Alright seems you updated recently @Anslem27 . I'll close this off
